### ISSUE TITLE
Docker configuration

### ISSUE THREAD

**Issue by wrathematics** [smouksassi/ggplotwithyourdata#12]
Hi,

Nice shiny app! I wanted to use it as a demonstration for something, so I made a Docker configuration for it to make it easier to install/stand up.

* The configuration files https://github.com/wrathematics/ggplotwithyourdata-docker
* The build on Docker Hub https://hub.docker.com/r/wrathematics/ggplotwithyourdata-docker/

If you're interested, I can transfer ownership of the repo to you.  I could also PR/you could put the configuration in the source repo, under `./docker` or something, if you preferred. If not, that's fine too; feel free to close the issue.

**Comment by smouksassi** [comment]
Hi @wrathematics,
Thank you for the nice words and for contributing a Docker configuration I am willing to review a pull request and make it part of the main app so when the app is updated I make sure the docker is also up to date. Also if you have any special requests to make the app suit better your needs let me know
Bests,
Samer

**Comment by wrathematics** [comment]
Addressed in https://github.com/smouksassi/ggplotwithyourdata/pull/13
