### ISSUE TITLE
ERROR message 'ERROR: input string 1 is invalid UTF-8'

### ISSUE THREAD

**Issue by walsu** [smouksassi/ggplotwithyourdata#16]
I get the following error when I run shiny app after downloading the whole file to the desktop.
How can I solve this issue? Currently, I am using windows 10, RStudio 1.0.143, R 3.3.1.
![image](https://user-images.githubusercontent.com/9631440/28062024-94849694-6667-11e7-9803-a60c6f605db8.png)

**Comment by smouksassi** [comment]
Dear Walsu,
did you open the file and save it ? what windows local are you in ?
try to run directly from github and see if you still get encoding errors:
```r
shiny::runGitHub('ggplotwithyourdata', 'smouksassi', subdir = 'shinyapp')
```

**Comment by walsu** [comment]
Dear smouksassi,
I got same result. Did you mean the location of hard disk drive where I saved? At first I downloaded it to the 'download' folder (C:\Users\user\Downloads) and then I ran it on 'c :\' but I got the same result.
![image](https://user-images.githubusercontent.com/9631440/28096369-3809b404-66e3-11e7-8a91-c7f33fb710a2.png)
![image](https://user-images.githubusercontent.com/9631440/28096381-3f0cad10-66e3-11e7-9ca7-c7e8aac9f9e6.png)
![image](https://user-images.githubusercontent.com/9631440/28096525-7ec09b1e-66e4-11e7-98e0-f1a0439fff7d.png)

**Comment by smouksassi** [comment]
I meant which windows locake ?https://answers.microsoft.com/en-us/surface/forum/surfbook-surfaccess/how-to-change-system-locale-in-windows-10-the/d7826ef0-13cd-43ea-8e01-2846d813dfed                                                                                                                                       Samer                                                                                                                                                                            From: notifications@github.comSent: July 11, 2017 8:29 PMTo: ggplotwithyourdata@noreply.github.comReply-to: reply@reply.github.comCc: samermouksassi@gmail.com; comment@noreply.github.comSubject: Re: [smouksassi/ggplotwithyourdata] ERROR message 'ERROR: input string 1 is invalid UTF-8' (#16)  Dear smouksassi,
I got same result. Did you mean the location of hard disk drive where I saved? At first I downloaded it to the 'download' folder (C:\Users\user\Downloads) and then I ran it on 'c :' but I got the same result.

**Comment by walsu** [comment]
My system locale is 'Korea'. 
In google search as keyword 'input string 1 is invalid UTF-8 r', I got the following link  (https://stackoverflow.com/questions/3548090/facet-grid-problem-input-string-1-is-invalid-in -this-locale) and I changed as it says 'Sys.setlocale (locale = "C")'.
I did not know exactly why it was solved, but anyway this issue was resolved in my laptop. Can you explain why these locale option is important?

**Comment by smouksassi** [comment]
Ok I suspect some characters in the how to are making an error on your system can you try to navigate to text and howto.md
~\ggplotwithyourdata\shinyapp\text\howto.md

do to almost the end of the file and delete lines 52 and 53 the 12. bullet point it has some handy shortcut characters and html symbols that might be causing the error

12. Copy Paste Bonus ≤ ≥ µ m² ³
    HTML: &le; &ge; &mu; &plusmn; &deg; <sup>superscript</sup>

let me know if this solves your problem

**Comment by walsu** [comment]
I did not have any errors on my laptop anymore so I tested it on another laptop. As you said, when I delete the 52-53 rows in the 'howto.md' file, an error did not occur and an it occurs if I do not delete the line. Thank you.

**Comment by smouksassi** [comment]
great I will close the issue and keep in mind that this fails in certain OS locale I might just remove these lines completely since users should know how to type this characters on their OS and keyboard
