### ISSUE TITLE
Turn into a gadget?

### ISSUE THREAD

**Issue by talgalili** [smouksassi/ggplotwithyourdata#17]
It would be easier if one could simply run:
```r
launch_ggplotwithyourdata(mtcars)
```

**Comment by smouksassi** [comment]
Hi talgalili,
Thank you for taking the time to comment and file an issue.
The app was designed a full app not a gadget. The users are primarily non-coders. Even opening an rstudio session can be difficult for this population !
Can you describe more about your use case and whether you expect the gadget to work within a pane in Rstudio? How is this better than launching the app in chrome and loading your data there?
A gadget needs big design changes including miniUI etc. and is out of the scope of this app utility. But let us discuss a little bit about your vision and see whether we can fit some elements in ! 
Bests,
Samer

**Comment by daattali** [comment]
this is now a shiny app that can be called using `ggquickeda` package https://github.com/smouksassi/ggquickeda

**Comment by smouksassi** [comment]
closing this issue as it is now possible in ggquickeda
